name: forced_recog
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.1  # Adjust based on your CUDA version
  - pip
  - pip:
    - pandas
    - transformers
    - datasets
    - wandb
    - peft
    - tqdm
    - accelerate
    - python-dotenv
    - modal
    - pyyaml
    - matplotlib
    - seaborn
    - numpy
    - scikit-learn
