# Bradley-Terry Parameter Recovery Validation Configuration

# Experiment name (used for output filename)
args_name: "bt_validation_grid_9x9"

# Theta (setting preference) parameter grid
theta_min: -0.5      # Minimum theta value
theta_max: 0.5       # Maximum theta value  
theta_num: 9         # Number of theta grid points
theta_std: 0.5       # Standard deviation of noise added to theta

# Alpha (position bias) parameter grid
alpha_min: -5.0      # Minimum alpha value
alpha_max: 5.0       # Maximum alpha value
alpha_num: 9         # Number of alpha grid points  
alpha_std: 0.5       # Standard deviation of noise added to alpha

# Data generation parameters
num_data: 100        # Number of comparison pairs per experiment (200 total observations)
num_repeats: 5       # Number of times to repeat each grid point

# MCMC sampling parameters
n_samples: 2000      # Number of posterior samples
n_warmup: 1000       # Number of warmup samples

# Prior parameters (should match your real analysis)
theta_prior_sigma: 1.0    # Prior std for theta ~ N(0, theta_prior_sigma)
alpha_prior_sigma: 0.5    # Prior std for alpha ~ N(0, alpha_prior_sigma)